FROM osixia/phpldapadmin:0.6.8
MAINTAINER Chris Garrigues <cwg@deepeddy.com>

#ADD https-certs /container/service/phpldapadmin/assets/apache2/certs
#ADD ldap-certs /container/service/ldap-client/assets/certs
#ADD my-config.php /container/service/phpldapadmin/assets/config.php
ADD environment /container/environment/01-custom
